sudo: required
services:
- docker

before_install:
- docker build -t  test/docker_test -f Dockerfile.dev .

script:
- docker run test/docker_test npm run -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "???"
  bucket_path: "docker"
  on:
    branch: master

